DO $$
BEGIN
IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='iacsvc') THEN
   REVOKE ALL PRIVILEGES ON DATABASE postgres FROM iacsvc;
END IF;
END$$;DROP SCHEMA IF EXISTS iac CASCADE;
DROP ROLE IF EXISTS iacsvc;

CREATE ROLE iacsvc PASSWORD 'iacsvc' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA iac AUTHORIZATION iacsvc;

REVOKE ALL ON ALL TABLES IN SCHEMA iac FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA iac FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO iacsvc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA iac TO iacsvc;
GRANT ALL ON ALL SEQUENCES IN SCHEMA iac TO iacsvc;
