version: '3'

services:
  party:
    container_name: party
    build: ${RAS_HOME}/ras-party
    volumes:
      - ${RAS_HOME}/ras-party:/app
    ports:
      - "${PARTY_PORT}:${PARTY_PORT}"
    external_links:
     - postgres
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - AUTH_SERVICE_URL=http://${AUTH_HOST}:${AUTH_PORT}
      - CASE_SERVICE_URL=http://${CASE_HOST}:${CASE_PORT}
      - COLLECTION_EXERCISE_SERVICE_HOST=${COLLECTION_EXERCISE_HOST}
      - SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - IAC_SERVICE_HOST=${IAC_HOST}
      - AUTH_SERVICE_HOST=${AUTH_HOST}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PARTY_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  secure-message:
    container_name: secure-message
    build: ${RAS_HOME}/ras-secure-message
    volumes:
      - ${RAS_HOME}/ras-secure-message:/app
    ports:
      - "${SECURE_MESSAGE_PORT}:${SECURE_MESSAGE_PORT}"
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - SECURE_MESSAGING_DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SM_JWT_ENCRYPT=0
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NOTIFICATION_API_KEY=${NOTIFICATION_API_KEY}
      - NOTIFICATION_TEMPLATE_ID=${NOTIFICATION_TEMPLATE_ID}
      - SERVICE_ID=${SERVICE_ID}
      - PARTY_SERVICE_HOST=${PARTY_HOST}
      - PARTY_SERVICE_PORT=${PARTY_PORT}
      - CASE_SERVICE_HOST=${CASE_HOST}
      - CASE_SERVICE_PORT=${CASE_PORT}
      - USE_UAA=1
      - UAA_URL=http://${UAA_HOST}:${UAA_PORT}
      - CLIENT_ID=secure_message
      - CLIENT_SECRET=password
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SECURE_MESSAGE_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  frontstage:
    container_name: frontstage
    build: ${RAS_HOME}/ras-frontstage
    volumes:
      - ${RAS_HOME}/ras-frontstage:/app
    ports:
      - "${FRONTSTAGE_PORT}:${FRONTSTAGE_PORT}"
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - CASE_URL=http://${CASE_HOST}:${CASE_PORT}
      - COLLECTION_EXERCISE_URL=http://${COLLECTION_EXERCISE_HOST}:${COLLECTION_EXERCISE_PORT}
      - COLLECTION_INSTRUMENT_URL=http://${COLLECTION_INSTRUMENT_HOST}:${COLLECTION_INSTRUMENT_PORT}
      - EQ_URL=${EQ_URL}
      - IAC_URL=http://${IAC_HOST}:${IAC_PORT}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS_FRONTSTAGE}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - AUTH_URL=http://${AUTH_HOST}:${AUTH_PORT}
      - PARTY_URL=http://${PARTY_HOST}:${PARTY_PORT}
      - PORT=${FRONTSTAGE_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=3
      - SECURE_MESSAGE_URL=http://${SECURE_MESSAGE_HOST}:${SECURE_MESSAGE_PORT}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTSTAGE_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  collection-instrument:
    container_name: collection-instrument
    build: ${RAS_HOME}/ras-collection-instrument
    volumes:
      - ${RAS_HOME}/ras-collection-instrument:/app
    ports:
      - "${COLLECTION_INSTRUMENT_PORT}:${COLLECTION_INSTRUMENT_PORT}"
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS}
      - CONFIG_YML=config/config-docker.yaml
      - ONS_CRYPTOKEY=somethingsecure
      - CASE_URL=http://${CASE_HOST}:${CASE_PORT}
      - COLLECTION_EXERCISE_URL=http://${COLLECTION_EXERCISE_HOST}:${COLLECTION_EXERCISE_PORT}
      - PARTY_URL=http://${PARTY_HOST}:${PARTY_PORT}
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
      - RABBITMQ_AMQP_SURVEY_RESPONSE=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
      - RABBITMQ_AMQP_COLLECTION_INSTRUMENT=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
    networks:
      - rasrmdockerdev_default
    external_links:
      - postgres:ras-postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${COLLECTION_INSTRUMENT_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  respondent-home-ui:
    container_name: respondent-home-ui
    build: ${RAS_HOME}/respondent-home-ui
    volumes:
      - ${RAS_HOME}/respondent-home-ui:/app
    ports:
      - 9092:9092
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - ACCOUNT_SERVICE_URL=http://localhost:9092
      - CASE_URL=http://${CASE_HOST}:${CASE_PORT}
      - CASE_USERNAME=${SECURITY_USER_NAME}
      - CASE_PASSWORD=${SECURITY_USER_PASSWORD}
      - COLLECTION_EXERCISE_URL=http://${COLLECTION_EXERCISE_HOST}:${COLLECTION_EXERCISE_PORT}
      - COLLECTION_EXERCISE_USERNAME=${SECURITY_USER_NAME}
      - COLLECTION_EXERCISE_PASSWORD=${SECURITY_USER_PASSWORD}
      - COLLECTION_INSTRUMENT_URL=http://${COLLECTION_INSTRUMENT_HOST}:${COLLECTION_INSTRUMENT_PORT}
      - COLLECTION_INSTRUMENT_USERNAME=${SECURITY_USER_NAME}
      - COLLECTION_INSTRUMENT_PASSWORD=${SECURITY_USER_PASSWORD}
      - IAC_URL=http://${IAC_HOST}:${IAC_PORT}
      - IAC_USERNAME=${SECURITY_USER_NAME}
      - IAC_PASSWORD=${SECURITY_USER_PASSWORD}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS_RH}
      - SAMPLE_URL=http://${SAMPLE_HOST}:${SAMPLE_PORT}
      - SAMPLE_USERNAME=${SECURITY_USER_NAME}
      - SAMPLE_PASSWORD=${SECURITY_USER_PASSWORD}
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
      - SURVEY_USERNAME=${SECURITY_USER_NAME}
      - SURVEY_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  response-operations-ui:
    container_name: response-operations-ui
    build: ${RAS_HOME}/response-operations-ui
    volumes:
      - ${RAS_HOME}/response-operations-ui:/app
    ports:
      - 8085:8085
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - CASE_URL=http://${CASE_HOST}:${CASE_PORT}
      - COLLECTION_EXERCISE_URL=http://${COLLECTION_EXERCISE_HOST}:${COLLECTION_EXERCISE_PORT}
      - COLLECTION_INSTRUMENT_URL=http://${COLLECTION_INSTRUMENT_HOST}:${COLLECTION_INSTRUMENT_PORT}
      - IAC_URL=http://${IAC_HOST}:${IAC_PORT}
      - PARTY_URL=http://${PARTY_HOST}:${PARTY_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=3
      - REPORT_URL=http://${REPORTING_HOST}:${REPORTING_PORT}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - SAMPLE_URL=http://${SAMPLE_HOST}:${SAMPLE_PORT}
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
      - SECURE_MESSAGE_URL=http://${SECURE_MESSAGE_HOST}:${SECURE_MESSAGE_PORT}
      - TEMPLATES_AUTO_RELOAD=True
      - EXPLAIN_TEMPLATE_LOADING=True
      - SECURE_MESSAGING_JWT_SECRET=${JWT_SECRET}
      - UAA_SERVICE_URL=http://${UAA_HOST}:${UAA_PORT}
      - UAA_CLIENT_ID=response_operations
      - UAA_CLIENT_SECRET=password
    external_links:
      - redis
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  response-operations-social-ui:
    container_name: response-operations-social-ui
    build: ${RAS_HOME}/response-operations-social-ui
    volumes:
      - ${RAS_HOME}/response-operations-social-ui:/app
    ports:
      - 8086:8086
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - CASE_URL=http://${CASE_HOST}:${CASE_PORT}
      - CASE_USERNAME=${SECURITY_USER_NAME}
      - CASE_PASSWORD=${SECURITY_USER_PASSWORD}
      - COLLECTION_EXERCISE_URL=http://${COLLECTION_EXERCISE_HOST}:${COLLECTION_EXERCISE_PORT}
      - COLLECTION_EXERCISE_USERNAME=${SECURITY_USER_NAME}
      - COLLECTION_EXERCISE_PASSWORD=${SECURITY_USER_PASSWORD}
      - COLLECTION_INSTRUMENT_URL=http://${COLLECTION_INSTRUMENT_HOST}:${COLLECTION_INSTRUMENT_PORT}
      - COLLECTION_INSTRUMENT_USERNAME=${SECURITY_USER_NAME}
      - COLLECTION_INSTRUMENT_PASSWORD=${SECURITY_USER_PASSWORD}
      - IAC_URL=http://${IAC_HOST}:${IAC_PORT}
      - IAC_USERNAME=${SECURITY_USER_NAME}
      - IAC_PASSWORD=${SECURITY_USER_PASSWORD}
      - PARTY_URL=http://${PARTY_HOST}:${PARTY_PORT}
      - PARTY_USERNAME=${SECURITY_USER_NAME}
      - PARTY_PASSWORD=${SECURITY_USER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=3
      - SAMPLE_URL=http://${SAMPLE_HOST}:${SAMPLE_PORT}
      - SAMPLE_USERNAME=${SECURITY_USER_NAME}
      - SAMPLE_PASSWORD=${SECURITY_USER_PASSWORD}
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
      - SURVEY_USERNAME=${SECURITY_USER_NAME}
      - SURVEY_PASSWORD=${SECURITY_USER_PASSWORD}
      - SECURE_MESSAGE_URL=http://${SECURE_MESSAGE_HOST}:${SECURE_MESSAGE_PORT}
      - TEMPLATES_AUTO_RELOAD=True
      - EXPLAIN_TEMPLATE_LOADING=True
      - SECURE_MESSAGING_JWT_SECRET=${JWT_SECRET}
      - UAA_SERVICE_URL=http://${UAA_HOST}:${UAA_PORT}
      - UAA_CLIENT_ID=response_operations_social
      - UAA_CLIENT_SECRET=password
    external_links:
      - redis
    networks:
      - rasrmdockerdev_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
   rasrmdockerdev_default:
     external: true
