version: '3'

services:
  frontstage-api:
    container_name: frontstage-api
    image: sdcplatform/ras-frontstage-api
    ports:
      - "${FRONTSTAGE_API_PORT}:${FRONTSTAGE_API_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - DJANGO_CLIENT_ID=${DJANGO_CLIENT_ID}
      - DJANGO_CLIENT_SECRET=${DJANGO_CLIENT_SECRET}
      - RM_CASE_SERVICE_HOST=${CASE_HOST}
      - RM_CASE_SERVICE_PORT=${CASE_PORT}
      - RM_CASE_SERVICE_PROTOCOL=http
      - RAS_SECURE_MESSAGE_SERVICE_HOST=secure-message
      - RAS_SECURE_MESSAGE_SERVICE_PORT=${SECURE_MESSAGE_PORT}
      - RAS_SECURE_MESSAGE_SERVICE_PROTOCOL=http
      - RAS_PARTY_SERVICE_HOST=${PARTY_HOST}
      - RAS_PARTY_SERVICE_PORT=${PARTY_PORT}
      - RAS_PARTY_SERVICE_PROTOCOL=http
      - RAS_OAUTH_SERVICE_HOST=oauth2-service
      - RAS_OAUTH_SERVICE_PORT=${OAUTH_PORT}
      - RAS_OAUTH_SERVICE_PROTOCOL=http
      - RM_IAC_SERVICE_HOST=${IAC_HOST}
      - RM_IAC_SERVICE_PORT=${IAC_PORT}
      - RM_IAC_SERVICE_PROTOCOL=http
      - RM_COLLECTION_EXERCISE_SERVICE_HOST=${COLLEX_HOST}
      - RM_COLLECTION_EXERCISE_SERVICE_PORT=${COLLEX_PORT}
      - RM_COLLECTION_EXERCISE_SERVICE_PROTOCOL=http
      - RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RM_SURVEY_SERVICE_PORT=${SURVEY_PORT}
      - RM_SURVEY_SERVICE_PROTOCOL=http
      - RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=${COLL_INST_HOST}
      - RAS_COLLECTION_INSTRUMENT_SERVICE_PORT=${COLLECTION_INSTRUMENT_PORT}
      - RAS_COLLECTION_INSTRUMENT_SERVICE_PROTOCOL=http
    networks:
      - rasrmdockerdev_default

  party-service:
    container_name: party-service
    image: sdcplatform/ras-party
    ports:
      - "${PARTY_PORT}:${PARTY_PORT}"
    external_links:
     - postgres
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - RAS_OAUTH_SERVICE_PORT=8040
      - RAS_OAUTH_CLIENT_ID=ons@ons.gov
      - RAS_OAUTH_CLIENT_SECRET=password
      - RAS_CASE_SERVICE_HOST=casesvc
      - RAS_COLLEX_SERVICE_HOST=collex
      - RAS_SURVEY_SERVICE_HOST=survey
      - RAS_API_GATEWAY_HOST=api-gateway
      - RAS_IAC_SERVICE_HOST=iac
      - RAS_OAUTH_SERVICE_HOST=oauth2-service
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasrmdockerdev_default

  secure-message-service:
    container_name: secure-message
    image: sdcplatform/ras-secure-message
    ports:
      - "${SECURE_MESSAGE_PORT}:${SECURE_MESSAGE_PORT}"
    environment:
      - SECURE_MESSAGING_DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_SM_HOST}:${POSTGRES_PORT}/postgres
      - SM_JWT_ENCRYPT=0
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasrmdockerdev_default

  frontstage:
    container_name: frontstage
    image: sdcplatform/ras-frontstage
    ports:
      - "${FRONTSTAGE_PORT}:${FRONTSTAGE_PORT}"
    environment:
      -  API_GATEWAY_CASE_URL=http://casesvc:8171/cases/
      -  API_GATEWAY_COLLECTION_EXERCISE_URL=http://collex:8145/collectionexercises/
      -  API_GATEWAY_SURVEYS_URL=http://survey:8080/surveys/
      -  API_GATEWAY_IAC_URL=http://iac:8121/iacs/
      -  API_GATEWAY_COLLECTION_INSTRUMENT_URL=http://collection-instrument:8082/collection-instrument-api/1.0.2/
      -  API_GATEWAY_AGGREGATED_SURVEYS_URL=http://survey:8083/api/1.0.0/surveys/
      -  API_GATEWAY_PARTY_URL=http://party-service:8081/party-api/v1/
      -  OAUTHLIB_INSECURE_TRANSPORT=1
      -  ONS_OAUTH_PROTOCOL=http
      -  ONS_OAUTH_HOST=oauth2-service
      -  ONS_OAUTH_PORT=8040
      -  RAS_FRONTSTAGE_CLIENT_ID=ons@ons.gov
      -  RAS_FRONTSTAGE_CLIENT_SECRET=password
      -  RM_CASE_SERVICE_HOST=casesvc
      -  RM_CASE_SERVICE_PORT=8171
      -  RM_CASE_SERVICE_PROTOCOL=http
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=collection-instrument
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PORT=8082
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PROTOCOL=http
      -  RAS_API_GATEWAY_SERVICE_HOST=api-gateway
      -  RAS_API_GATEWAY_SERVICE_PORT=8083
      -  RAS_API_GATEWAY_SERVICE_PROTOCOL=http
      -  RM_IAC_SERVICE_HOST=iac
      -  RM_IAC_SERVICE_PORT=8121
      -  RM_IAC_SERVICE_PROTOCOL=http
      -  RAS_PARTY_SERVICE_HOST=party-service
      -  RAS_PARTY_SERVICE_PORT=8081
      -  RAS_PARTY_SERVICE_PROTOCOL=http
      -  RM_COLLECTION_EXERCISE_SERVICE_HOST=collex
      -  RM_COLLECTION_EXERCISE_SERVICE_PORT=8145
      -  RM_COLLECTION_EXERCISE_SERVICE_PROTOCOL=http
      -  RM_SURVEY_SERVICE_HOST=survey
      -  RM_SURVEY_SERVICE_PORT=8080
      -  RM_SURVEY_SERVICE_PROTOCOL=http
      -  RAS_SECURE_MESSAGE_SERVICE_HOST=secure-message
      -  RAS_SECURE_MESSAGE_SERVICE_PORT=5050
      -  RAS_SECURE_MESSAGE_SERVICE_PROTOCOL=http
      -  FS_DEV_PORT=5001
      -  SECURITY_USER_NAME=${SECURITY_USER_NAME}
      -  SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      -  RAS_FRONTSTAGE_API_HOST=frontstage-api
      -  RAS_FRONTSTAGE_API_PORT=8083
      -  REDIS_HOST=redis
      -  REDIS_PORT=6379
    networks:
      - rasrmdockerdev_default

  collection-instrument-service:
    container_name: collection-instrument
    image: sdcplatform/ras-collection-instrument
    ports:
      - "${COLLECTION_INSTRUMENT_PORT}:${COLLECTION_INSTRUMENT_PORT}"
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - API_GATEWAY_CASE_URL=http://casesvc:8171/cases/
      - API_GATEWAY_COLLECTION_EXERCISE_URL=http://collex:8145/collectionexercises/
      - API_GATEWAY_SURVEY_SERVICE_URL=http://survey:8080/surveys/
      - RABBITMQ_AMQP=amqp://guest:guest@rabbitmq:5672
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS}
      - CONFIG_YML=config/config-docker.yaml
    networks:
      - rasrmdockerdev_default
    external_links:
      - postgres:ras-postgres

  backstage:
    container_name: backstage
    image: sdcplatform/ras-backstage
    ports:
      - "${BACKSTAGE_PORT}:${BACKSTAGE_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RM_SURVEY_SERVICE_PORT=${SURVEY_PORT}
    networks:
      - rasrmdockerdev_default

  oauth2-service:
    container_name: oauth2-service
    image: sdcplatform/django-oauth2-test
    ports:
      - 8040:8040
    environment:
      - OAUTH2_SUPER_USER=admin
      - OAUTH2_SUPER_USER_PASSWORD=admin2017
      - OAUTH2_SUPER_USER_EMAIL=admin@email.com
      - DJANGO_SETTINGS_MODULE=proj.settings.docker
    external_links:
      - postgres:ras-postgres
    networks:
      - rasrmdockerdev_default

  response-operations-ui:
    container_name: response-operations-ui
    image: sdcplatform/response-operations-ui
    ports:
      - 8085:8085
    environment:
      - BACKSTAGE_API_URL=http://backstage:${BACKSTAGE_PORT}/backstage-api/v1
    external_links:
      - backstage:backstage
    networks:
      - rasrmdockerdev_default

networks:
   rasrmdockerdev_default:
     external: true
