version: '3'

services:
  frontstage-api:
    container_name: frontstage-api
    image: sdcplatform/ras-frontstage-api
    ports:
      - "${FRONTSTAGE_API_PORT}:${FRONTSTAGE_API_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - DJANGO_CLIENT_ID=${DJANGO_CLIENT_ID}
      - DJANGO_CLIENT_SECRET=${DJANGO_CLIENT_SECRET}
      - RM_CASE_SERVICE_HOST=${CASE_HOST}
      - RM_CASE_SERVICE_PORT=${CASE_PORT}
      - RM_CASE_SERVICE_PROTOCOL=http
      - RAS_SECURE_MESSAGE_SERVICE_HOST=${SECURE_MESSAGE_HOST}
      - RAS_SECURE_MESSAGE_SERVICE_PORT=${SECURE_MESSAGE_PORT}
      - RAS_SECURE_MESSAGE_SERVICE_PROTOCOL=http
      - RAS_PARTY_SERVICE_HOST=${PARTY_HOST}
      - RAS_PARTY_SERVICE_PORT=${PARTY_PORT}
      - RAS_PARTY_SERVICE_PROTOCOL=http
      - RAS_OAUTH_SERVICE_HOST=${OAUTH_HOST}
      - RAS_OAUTH_SERVICE_PORT=${OAUTH_PORT}
      - RAS_OAUTH_SERVICE_PROTOCOL=http
      - RM_IAC_SERVICE_HOST=${IAC_HOST}
      - RM_IAC_SERVICE_PORT=${IAC_PORT}
      - RM_IAC_SERVICE_PROTOCOL=http
      - RM_COLLECTION_EXERCISE_SERVICE_HOST=${COLLEX_HOST}
      - RM_COLLECTION_EXERCISE_SERVICE_PORT=${COLLEX_PORT}
      - RM_COLLECTION_EXERCISE_SERVICE_PROTOCOL=http
      - RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RM_SURVEY_SERVICE_PORT=${SURVEY_PORT}
      - RM_SURVEY_SERVICE_PROTOCOL=http
      - RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=${COLL_INST_HOST}
      - RAS_COLLECTION_INSTRUMENT_SERVICE_PORT=${COLL_INST_PORT}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS_FRONTSTAGE}
      - EQ_URL=https://eq-test/session?token=
      - RAS_COLLECTION_INSTRUMENT_SERVICE_PROTOCOL=http
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTSTAGE_API_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  party-service:
    container_name: party-service
    image: sdcplatform/ras-party
    ports:
      - "${PARTY_PORT}:${PARTY_PORT}"
    external_links:
     - postgres
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - RAS_OAUTH_SERVICE_PORT=${OAUTH_PORT}
      - RAS_OAUTH_CLIENT_ID=ons@ons.gov
      - RAS_OAUTH_CLIENT_SECRET=password
      - RAS_CASE_SERVICE_HOST=${CASE_HOST}
      - RAS_COLLEX_SERVICE_HOST=${COLLEX_HOST}
      - RAS_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RAS_IAC_SERVICE_HOST=${IAC_HOST}
      - RAS_OAUTH_SERVICE_HOST=${OAUTH_HOST}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PARTY_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  secure-message-service:
    container_name: secure-message
    image: sdcplatform/ras-secure-message
    ports:
      - "${SECURE_MESSAGE_PORT}:${SECURE_MESSAGE_PORT}"
    environment:
      - SECURE_MESSAGING_DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SM_JWT_ENCRYPT=0
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NOTIFICATION_API_KEY=${NOTIFICATION_API_KEY}
      - NOTIFICATION_TEMPLATE_ID=${NOTIFICATION_TEMPLATE_ID}
      - SERVICE_ID=${SERVICE_ID}
      - RAS_PARTY_SERVICE_HOST=${PARTY_HOST}
      - RAS_PARTY_SERVICE_PORT=${PARTY_PORT}
      - RM_CASE_SERVICE_HOST=${CASE_HOST}
      - RM_CASE_SERVICE_PORT=${CASE_PORT}
      - USE_UAA=1
      - UAA_URL=http://${UAA_HOST}:${UAA_PORT}
      - CLIENT_ID=secure_message
      - CLIENT_SECRET=password
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SECURE_MESSAGE_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  frontstage:
    container_name: frontstage
    image: sdcplatform/ras-frontstage
    ports:
      - "${FRONTSTAGE_PORT}:${FRONTSTAGE_PORT}"
    environment:
      -  OAUTHLIB_INSECURE_TRANSPORT=1
      -  ONS_OAUTH_PROTOCOL=http
      -  ONS_OAUTH_HOST=${OAUTH_HOST}
      -  ONS_OAUTH_PORT=${OAUTH_PORT}
      -  RAS_FRONTSTAGE_CLIENT_ID=ons@ons.gov
      -  RAS_FRONTSTAGE_CLIENT_SECRET=password
      -  RM_CASE_SERVICE_HOST=${CASE_HOST}
      -  RM_CASE_SERVICE_PORT=${CASE_PORT}
      -  RM_CASE_SERVICE_PROTOCOL=http
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=${COLL_INST_HOST}
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PORT=${COLL_INST_PORT}
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PROTOCOL=http
      -  RM_IAC_SERVICE_HOST=${IAC_HOST}
      -  RM_IAC_SERVICE_PORT=${IAC_PORT}
      -  RM_IAC_SERVICE_PROTOCOL=http
      -  RAS_PARTY_SERVICE_HOST=${PARTY_HOST}
      -  RAS_PARTY_SERVICE_PORT=${PARTY_PORT}
      -  RAS_PARTY_SERVICE_PROTOCOL=http
      -  RM_COLLECTION_EXERCISE_SERVICE_HOST=${COLLEX_HOST}
      -  RM_COLLECTION_EXERCISE_SERVICE_PORT=${COLLEX_PORT}
      -  RM_COLLECTION_EXERCISE_SERVICE_PROTOCOL=http
      -  RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      -  RM_SURVEY_SERVICE_PORT=${SURVEY_PORT}
      -  RM_SURVEY_SERVICE_PROTOCOL=http
      -  RAS_SECURE_MESSAGE_SERVICE_HOST=${SECURE_MESSAGE_HOST}
      -  RAS_SECURE_MESSAGE_SERVICE_PORT=${SECURE_MESSAGE_PORT}
      -  RAS_SECURE_MESSAGE_SERVICE_PROTOCOL=http
      -  SECURITY_USER_NAME=${SECURITY_USER_NAME}
      -  SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      -  RAS_FRONTSTAGE_API_HOST=${FRONTSTAGE_API_HOST}
      -  RAS_FRONTSTAGE_API_PORT=${FRONTSTAGE_API_PORT}
      -  REDIS_HOST=${REDIS_HOST}
      -  REDIS_PORT=${REDIS_PORT}
      -  PORT=8082
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTSTAGE_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  collection-instrument-service:
    container_name: collection-instrument
    image: sdcplatform/ras-collection-instrument
    ports:
      - "${COLL_INST_PORT}:${COLL_INST_PORT}"
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JSON_SECRET_KEYS=${JSON_SECRET_KEYS}
      - CONFIG_YML=config/config-docker.yaml
      - ONS_CRYPTOKEY=somethingsecure
      - COLLECTION_EXERCISE_HOST=${COLLEX_HOST}
      - CASE_SERVICE_HOST=${CASE_HOST}
      - PARTY_SERVICE_HOST=${PARTY_HOST}
      - PARTY_SERVICE_PORT=${PARTY_PORT}
      - RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RABBITMQ_AMQP_SURVEY_RESPONSE=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
      - RABBITMQ_AMQP_COLLECTION_INSTRUMENT=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
    networks:
      - rasrmdockerdev_default
    external_links:
      - postgres:ras-postgres
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${COLL_INST_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  backstage:
    container_name: backstage
    image: sdcplatform/ras-backstage
    ports:
      - "${BACKSTAGE_PORT}:${BACKSTAGE_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - RM_SURVEY_SERVICE_HOST=${SURVEY_HOST}
      - RM_SURVEY_SERVICE_PORT=${SURVEY_PORT}
      - RM_COLLECTION_EXERCISE_SERVICE_HOST=${COLLEX_HOST}
      - RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=${COLL_INST_HOST}
      - RM_SAMPLE_SERVICE_HOST=${SAMPLE_HOST}
      - RM_SAMPLE_SERVICE_PORT=${SAMPLE_PORT}
      - RAS_PARTY_SERVICE_HOST=${PARTY_HOST}
      - RM_CASE_SERVICE_HOST=${CASE_HOST}
      - RM_IAC_SERVICE_HOST=${IAC_HOST}
      - USE_UAA=1
      - UAA_SERVICE_URL=http://${UAA_HOST}:${UAA_PORT}
      - UAA_CLIENT_ID=ras_backstage
      - UAA_CLIENT_SECRET=password
    networks:
      - rasrmdockerdev_default
    external_links:
      - uaa
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKSTAGE_PORT}/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  oauth2-service:
    container_name: oauth2-service
    image: sdcplatform/django-oauth2-test
    ports:
      - 8040:8040
    environment:
      - OAUTH2_SUPER_USER=admin
      - OAUTH2_SUPER_USER_PASSWORD=admin2017
      - OAUTH2_SUPER_USER_EMAIL=admin@email.com
      - DJANGO_SETTINGS_MODULE=proj.settings.docker
    external_links:
      - postgres:ras-postgres
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  response-operations-ui:
    container_name: response-operations-ui
    image: sdcplatform/response-operations-ui
    ports:
      - 8085:8085
    environment:
      - BACKSTAGE_API_URL=http://${BACKSTAGE_HOST}:${BACKSTAGE_PORT}/backstage-api
      - SURVEY_URL=http://${SURVEY_HOST}:${SURVEY_PORT}
      - SURVEY_USERNAME=${SECURITY_USER_NAME}
      - SURVEY_PASSWORD=${SECURITY_USER_PASSWORD}
      - RAS_SECURE_MESSAGING_JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=3
      - SECURE_MESSAGE_URL=http://${SECURE_MESSAGE_HOST}:${SECURE_MESSAGE_PORT}
      - UAA_SERVICE_URL=http://${UAA_HOST}:${UAA_PORT}
      - COLLECTION_EXERCISE_URL=http://${COLLEX_HOST}:${COLLEX_PORT}
      - COLLECTION_EXERCISE_USERNAME=${COLLECTION_EXERCISE_USERNAME}
      - COLLECTION_EXERCISE_PASSWORD=${COLLECTION_EXERCISE_PASSWORD}
    external_links:
      - backstage:backstage
      - redis
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
   rasrmdockerdev_default:
     external: true
