version: '3'
services:
  sample:
    container_name: sample
    image: sdcplatform/samplesvc
    ports:
     - "${SAMPLE_PORT}:8125"
     - "${SAMPLE_DEBUG_PORT}:5125"
     - "${SAMPLE_MAN_PORT}:8225"
    external_links:
     - postgres
     - rabbitmq
     - redis
     - sftp
     - party
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - liquibase_url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - REDIS_HOST=${REDIS_HOST}
     - REDIS_PORT=${REDIS_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - SFTP_HOST=${SFTP_HOST}
     - SFTP_PORT=${SFTP_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_HOST=${PARTY_HOST}
     - PARTY_SVC_CONNECTION_CONFIG_PORT=${PARTY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_USERNAME=${PARTY_USER}
     - PARTY_SVC_CONNECTION_CONFIG_PASSWORD=${PARTY_PASSWORD}
     - SAMPLE_UNIT_DISTRIBUTION_DELAY_MILLI_SECONDS=1000
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${SAMPLE_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8125/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  case:
    container_name: casesvc
    image: sdcplatform/casesvc
    ports:
     - "${CASE_PORT}:8171"
     - "${CASE_DEBUG_PORT}:5171"
     - "${CASE_MAN_PORT}:8271"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - ACTION_SVC_CONNECTION_CONFIG_HOST=${ACTION_HOST}
     - ACTION_SVC_CONNECTION_CONFIG_PORT=${ACTION_PORT}
     - INTERNET_ACCESS_CODE_SVC_CONNECTION_CONFIG_HOST=${IAC_HOST}
     - INTERNET_ACCESS_CODE_SVC_CONNECTION_CONFIG_PORT=${IAC_PORT}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_HOST=${COLLEX_HOST}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_PORT=${COLLEX_PORT}
     - CASE_DISTRIBUTION_DELAY_MILLI_SECONDS=30000
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${CASE_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8171/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  action:
    container_name: action
    image: sdcplatform/actionsvc
    ports:
     - "${ACTION_PORT}:8151"
     - "${ACTION_DEBUG_PORT}:5151"
     - "${ACTION_MAN_PORT}:8251"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - CASE_SVC_CONNECTION_CONFIG_HOST=${CASE_HOST}
     - CASE_SVC_CONNECTION_CONFIG_PORT=${CASE_PORT}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_HOST=${COLLEX_HOST}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_PORT=${COLLEX_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_HOST=${PARTY_HOST}
     - PARTY_SVC_CONNECTION_CONFIG_PORT=${PARTY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_USERNAME=${PARTY_USER}
     - PARTY_SVC_CONNECTION_CONFIG_PASSWORD=${PARTY_PASSWORD}
     - SURVEY_SVC_CONNECTION_CONFIG_HOST=${SURVEY_HOST}
     - SURVEY_SVC_CONNECTION-CONFIG_PORT=${SURVEY_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${ACTION_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8151/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  actionexporter:
    container_name: actionexporter
    image: sdcplatform/actionexportersvc
    ports:
     - "${ACTIONEXP_PORT}:8141"
     - "${ACTIONEXP_DEBUG_PORT}:5141"
     - "${ACTIONEXP_MAN_PORT}:8241"
    external_links:
     - postgres
     - rabbitmq
     - redis
     - sftp
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - SFTP_HOST=${SFTP_HOST}
     - SFTP_PORT=${SFTP_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${ACTIONEXP_DEBUG_PORT}
     - FREEMARKER_DELAYFORNEWTEMPLATES=3600000
     - DATA_GRID_LOCK_TIME_TO_LIVE_SECONDS=45
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8141/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  iac:
    container_name: iac
    image: sdcplatform/iacsvc 
    ports:
     - "${IAC_PORT}:8121"
     - "${IAC_DEBUG_PORT}:5121"
     - "${IAC_MAN_PORT}:8221"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - CASE_SVC_CONNECTION_CONFIG_HOST=${CASE_HOST}
     - CASE_SVC_CONNECTION_CONFIG_PORT=${CASE_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${IAC_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8121/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  sdx-gateway:
    container_name: sdx-gateway
    image: sdcplatform/sdx-gateway
    ports:
     - "8191:8191"
     - "5191:5191"
     - "8291:8291"
    external_links:
     - postgres
     - rabbitmq
     - redis
     - sftp
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - SFTP_HOST=${SFTP_HOST}
     - SFTP_PORT=${SFTP_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5191
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  collectionexercise:
    container_name: collex
    image: sdcplatform/collectionexercisesvc 
    ports:
     - "${COLLEX_PORT}:8145"
     - "${COLLEX_DEBUG_PORT}:5145"
     - "${COLLEX_MAN_PORT}:8245"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDISSON_CONFIG_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - SAMPLE_SVC_CONNECTION_CONFIG_HOST=${SAMPLE_HOST}
     - SAMPLE_SVC_CONNECTION_CONFIG_PORT=${SAMPLE_PORT}
     - SURVEY_SVC_CONNECTION_CONFIG_HOST=${SURVEY_HOST}
     - SURVEY_SVC_CONNECTION_CONFIG_PORT=${SURVEY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_HOST=${PARTY_HOST}
     - PARTY_SVC_CONNECTION_CONFIG_PORT=${PARTY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_USERNAME=${PARTY_USER}
     - PARTY_SVC_CONNECTION_CONFIG_PASSWORD=${PARTY_PASSWORD}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_HOST=${COLL_INST_HOST}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PORT=${COLL_INST_PORT}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_USERNAME=${SECURITY_USER_NAME}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PASSWORD=${SECURITY_USER_PASSWORD}
     - SCHEDULES_VALIDATION_SCHEDULE_DELAY_MILLI_SECONDS=1000
     - SCHEDULES_DISTRIBUTION_SCHEDULE_DELAY_MILLI_SECONDS=1000
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${COLLEX_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8145/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  survey:
    container_name: survey
    image: sdcplatform/surveysvc
    ports:
     - "${SURVEY_PORT}:8080"
    external_links:
     - postgres
    environment:
     - DATABASE_URL=postgres://postgres:postgres@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?sslmode=disable
     - security_user_name=${SURVEY_USER}
     - security_user_password=${SURVEY_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  notifygateway:
    container_name: notifygateway
    image: sdcplatform/notifygatewaysvc
    ports:
     - "${NOTIFY_GATEWAY_PORT}:8181"
     - "${NOTIFY_GATEWAY_DEBUG_PORT}:5181"
    external_links:
     - rabbitmq
     - postgres
    environment:
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${NOTIFY_GATEWAY_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-XGET", "http://localhost:8181/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  comms-template:
    container_name: comms-template
    image: sdcplatform/comms-template-svc
    ports:
     - "${COMMS_TEMPLATE_PORT}:${COMMS_TEMPLATE_PORT}"
    external_links:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-XGET", "http://localhost:8182/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  respondent-home-ui:
    container_name: respondent-home-ui
    image: sdcplatform/respondent-home-ui
    ports:
     - "${RESPONDENT_HOME_UI_PORT}:${RESPONDENT_HOME_UI_PORT}"
    environment:
      # - RESPONDENT_HOME_ANALYTICS_ACCOUNT=${RESPONDENT_HOME_ANALYTICS_ACCOUNT}
      # - RESPONDENT_HOME_EQ_HOST=${RESPONDENT_HOME_EQ_HOST}
      # - RESPONDENT_HOME_EQ_PORT=${RESPONDENT_HOME_EQ_PORT}
      # - RESPONDENT_HOME_EQ_PRIVATE_KEY=${RESPONDENT_HOME_EQ_PRIVATE_KEY}
      # - RESPONDENT_HOME_EQ_PROTOCOL=${RESPONDENT_HOME_EQ_PROTOCOL}
      # - RESPONDENT_HOME_EQ_PUBLIC_KEY=${RESPONDENT_HOME_EQ_PUBLIC_KEY}
      # - RESPONDENT_HOME_IAC_SERVICE_HOST=${IAC_HOST}
      # - RESPONDENT_HOME_IAC_SERVICE_PASSWORD=${IAC_PASSWORD}
      # - RESPONDENT_HOME_IAC_SERVICE_PORT=${IAC_PORT}
      # - RESPONDENT_HOME_IAC_SERVICE_PROTOCOL=${RESPONDENT_HOME_IAC_SERVICE_PROTOCOL}
      # - RESPONDENT_HOME_IAC_SERVICE_USER=${IAC_USERNAME}
      # - RESPONDENT_HOME_LOCALE=${RESPONDENT_HOME_LOCALE}

        RESPONDENT_HOME_ANALYTICS_ACCOUNT: "${RESPONDENT_HOME_ANALYTICS_ACCOUNT}"
        RESPONDENT_HOME_EQ_HOST: "${RESPONDENT_HOME_EQ_HOST}"
        RESPONDENT_HOME_EQ_PORT: "${RESPONDENT_HOME_EQ_PORT}"
        RESPONDENT_HOME_EQ_PROTOCOL: "${RESPONDENT_HOME_EQ_PROTOCOL}"
        RESPONDENT_HOME_IAC_SERVICE_HOST: "${IAC_HOST}"
        RESPONDENT_HOME_IAC_SERVICE_PROTOCOL: "${RESPONDENT_HOME_IAC_SERVICE_PROTOCOL}"
        RESPONDENT_HOME_IAC_SERVICE_PASSWORD: "${IAC_PASSWORD}"
        RESPONDENT_HOME_IAC_SERVICE_PORT: "${IAC_PORT}"
        RESPONDENT_HOME_IAC_SERVICE_USER: "${IAC_USERNAME}"
        RESPONDENT_HOME_LOCALE: "${RESPONDENT_HOME_LOCALE}"
        RESPONDENT_HOME_EQ_PRIVATE_KEY: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAq0rFub/fC2S4kcP4l9ivxgljh8l3hYOKG5z8mJ1cggoRqTaI
          peS3d8eM4zLpuY0Pp5GMulHdDTjfoguPOSB2OJiYUm8QFwiq2L4C92TsteRXaatJ
          WqORyH2KP8X7q09fqtuIiBXvD9kwA9Miid+Z9Q/Ye950GTaJEJ0norqZpZEcIRdm
          lZIelqXJxE8OV+HbEojccLU7RaL7avCeVnK3jhzQmofAmEF3rLqEWHpctyuO0TfE
          Ew8Obxs2+klsQWnsfq3LhB7grm3dbTrTWBOScPolFkuI7TbabIFcOxy0gxJHmF9T
          1aPaym/g0KVOLhfAEI52DV7q4cywHv4FCK6dBwIDAQABAoIBAB4/fP0ZMdT8O0+a
          UKrX2+pXvBi9bfrIyLmplj2JBE3+YzIDbEwHQJLJTUrNsdJPY6VOoZBBZoywL2WZ
          LviCj/3cjIF6FVhL8oeFvlZbnyVbpkgFtFVqLxM9gA1U8+VDhfxQ+iI15VpiGwWB
          4kaAktpgqvTsyomtRLUHW3l0BC/lTvf2nQw+TgjCp5DGy2VZPrzDonBIxppD12Du
          2a4FYukz2Pnz7vCFHpEepz+NWmmmfRHMs/LgxCCEk/LfE3ySUmNdagCB784BJxJM
          Nus1vrgurJE9MWOt1TQ8lyBNtpaGo5pTk0VFcvFwe5lNp+fiMXvi1nLOGqUyssLC
          Uxc1DYkCgYEA39n+FYNr86Xc8CcVUAQyr3MKDnk5TOTy6oUUXpJq0EZDoqguqRfg
          9iMlZyj/Qqzcot7AixwuBNFgALiEXspd3Q9uSLxuwLKsWeOrIsvUGZQwldItSID3
          7uwb8Qr3TOAZmOPipaQl71qcA4I08lq+Sp9Kfd0ENEW2WALTTC30fQUCgYEAw+Ro
          HAd6rxCIyDIh6nnk69PS9+iuR6H/6Bc0vU1aagszDQktpk0UDkjaaMQ6RHebjZjW
          szBrsD5EFT5GLxLj0vbUJvWzK6+6lqOzisdiIu0U11B3eL6NEvaAdsgSq9Qj4X6N
          rYh5x0W5E2VIoDAe1NiglJagiaHUvF82S15XL5sCgYEAkxI0P4oy+Md2m0nyVLoN
          WvxoFQ5MOVsKxk5dDa2BBAnGEi4RSgNoSA7bWiWzX+kWpONY+YywJ3YwbwjL30Nx
          2/VxbdRvp6c8WWqdW6UzWwLj0Otf2Qzy2ETELuAXjqiF6M+Ab3ejfNi5PAzmIHzC
          HWD+nicBxh4vKS/iB2ECCskCgYALtH40Do5aH5bMv5IfPKFdJg8ZGSIwzZFJAPn5
          xcF9TKYERWQg58InCFtknzUMGkmFMHjDxETrBw1yZ4IyFeLfHDiZC11lYt63WZjE
          1h0bESeJphk9ccVkOK58aoATHF34f2Nf1yPPsG7apdatG7L77OXLeySklLLtfpLz
          9fMnuQKBgFJClh2vNYFlNndXoV5NFPLNz1L5Wv5WNwWcuGO4iCsUh2jFVl43z459
          V7ZuRp//4vIzEONqqyLUFt1JZKuCwWQB2sRjKWpqRB07C0o243XefD5f7844nmXq
          H0xKMFRYjDqhFdTXFWVPnk/tu/MxoSTdK0FfsgUnjs+TGvN5TnBW
          -----END RSA PRIVATE KEY-----
        RESPONDENT_HOME_EQ_PUBLIC_KEY: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu4UO1frTr8LPyyKXkQNi
          ua4VrCeLec/sMkkYt7aFf/jMr2pTCNeyGGD0lp1JZp5u4fs3yVMoQTxfmswggYG/
          44pzNYK7+03GyvGbNrHcLXZ1nPETPhMPWobWOWlQ0YH9vLCLD4nuFUS7ma5qTiRX
          y/UKPPvs5MSYj5EOFqkqziToTzsQ9LJewsLODSvQuILcX9Ygb0seq9zxesEoOPgz
          0xhxht8kTIp24UMhax1QAwOtqjkiShUOnj8xnXjGoc1GOJSSLDGm9dxaOt1F4uC5
          ddIEdYRuxd9A7yWjP1I8jWC/DSq8UEAooVfe6XNsoWWF2zn9XDjhWw0hwEXSX/QT
          9wIDAQAB
          -----END PUBLIC KEY-----

    restart: always

networks:
  default:
    external:
      name: rasrmdockerdev_default
