version: '3'
services:
  case:
    container_name: casesvc
    image: eu.gcr.io/census-ci/rm/census-rm-casesvc
    ports:
     - "${CASE_PORT}:8171"
     - "${CASE_DEBUG_PORT}:5171"
     - "${CASE_MAN_PORT}:8271"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - ACTION_SVC_CONNECTION_CONFIG_HOST=${ACTION_HOST}
     - ACTION_SVC_CONNECTION_CONFIG_PORT=${ACTION_PORT}
     - INTERNET_ACCESS_CODE_SVC_CONNECTION_CONFIG_HOST=${IAC_HOST}
     - INTERNET_ACCESS_CODE_SVC_CONNECTION_CONFIG_PORT=${IAC_PORT}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_HOST=${COLLEX_HOST}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_PORT=${COLLEX_PORT}
     - CASE_DISTRIBUTION_DELAY_MILLI_SECONDS=30000
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${CASE_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8171/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  action:
    container_name: action
    image: eu.gcr.io/census-ci/rm/census-rm-actionsvc
    ports:
     - "${ACTION_PORT}:8151"
     - "${ACTION_DEBUG_PORT}:5151"
     - "${ACTION_MAN_PORT}:8251"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - CASE_SVC_CONNECTION_CONFIG_HOST=${CASE_HOST}
     - CASE_SVC_CONNECTION_CONFIG_PORT=${CASE_PORT}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_HOST=${COLLEX_HOST}
     - COLLECTION_EXERCISE_SVC_CONNECTION_CONFIG_PORT=${COLLEX_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_HOST=${PARTY_HOST}
     - PARTY_SVC_CONNECTION_CONFIG_PORT=${PARTY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_USERNAME=${PARTY_USER}
     - PARTY_SVC_CONNECTION_CONFIG_PASSWORD=${PARTY_PASSWORD}
     - SURVEY_SVC_CONNECTION_CONFIG_HOST=${SURVEY_HOST}
     - SURVEY_SVC_CONNECTION-CONFIG_PORT=${SURVEY_PORT}
     - SAMPLE_SVC_CONNECTION_CONFIG_HOST=${SAMPLE_HOST}
     - SAMPLE_SVC_CONNECTION_CONFIG_PORT=${SAMPLE_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${ACTION_DEBUG_PORT} -Dlogging.level.uk.gov.ons.ctp.response.action.scheduled.plan.PlanScheduler=WARN -Dlogging.level.uk.gov.ons.ctp.response.action.service.impl.ActionPlanJobServiceImpl=WARN
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8151/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  collectionexercise:
    container_name: collex
    image: eu.gcr.io/census-ci/rm/census-rm-collectionexercisesvc
    ports:
     - "${COLLEX_PORT}:8145"
     - "${COLLEX_DEBUG_PORT}:5145"
     - "${COLLEX_MAN_PORT}:8245"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDISSON_CONFIG_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - ACTION_SVC_CONNECTION_CONFIG_HOST=${ACTION_HOST}
     - ACTION_SVC_CONNECTION_CONFIG_PORT=${ACTION_PORT}
     - SAMPLE_SVC_CONNECTION_CONFIG_HOST=${SAMPLE_HOST}
     - SAMPLE_SVC_CONNECTION_CONFIG_PORT=${SAMPLE_PORT}
     - SURVEY_SVC_CONNECTION_CONFIG_HOST=${SURVEY_HOST}
     - SURVEY_SVC_CONNECTION_CONFIG_PORT=${SURVEY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_HOST=${PARTY_HOST}
     - PARTY_SVC_CONNECTION_CONFIG_PORT=${PARTY_PORT}
     - PARTY_SVC_CONNECTION_CONFIG_USERNAME=${PARTY_USER}
     - PARTY_SVC_CONNECTION_CONFIG_PASSWORD=${PARTY_PASSWORD}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_HOST=${COLL_INST_HOST}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PORT=${COLL_INST_PORT}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_USERNAME=${SECURITY_USER_NAME}
     - COLLECTION_INSTRUMENT_SVC_CONNECTION_CONFIG_PASSWORD=${SECURITY_USER_PASSWORD}
     - SCHEDULES_VALIDATION_SCHEDULE_DELAY_MILLI_SECONDS=1000
     - SCHEDULES_DISTRIBUTION_SCHEDULE_DELAY_MILLI_SECONDS=1000
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${COLLEX_DEBUG_PORT}
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8145/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  survey:
    container_name: survey
    image: eu.gcr.io/census-ci/rm/census-rm-surveysvc
    ports:
     - "${SURVEY_PORT}:8080"
    external_links:
     - postgres
    environment:
     - DATABASE_URL=postgres://postgres:postgres@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?sslmode=disable
     - security_user_name=${SURVEY_USER}
     - security_user_password=${SURVEY_PASSWORD}
     - ZIPKIN_DSN=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v1/spans
     - ZIPKIN_SAMPLE_RATE=1.0
     - ZIPKIN_DISABLE=False
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  default:
    external:
      name: rasrmdockerdev_default
