DO $$
BEGIN
IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='samplesvc') THEN
   REVOKE ALL PRIVILEGES ON DATABASE postgres FROM samplesvc;
END IF;
END$$;
DROP SCHEMA IF EXISTS sample CASCADE;
DROP ROLE IF EXISTS samplesvc;

CREATE ROLE samplesvc PASSWORD 'samplesvc' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA sample AUTHORIZATION samplesvc;

REVOKE ALL ON ALL TABLES IN SCHEMA sample FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA sample FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO samplesvc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sample TO samplesvc;
GRANT ALL ON ALL SEQUENCES IN SCHEMA sample TO samplesvc;
